### ISSUE TITLE
Is this website designed for large displays?

### ISSUE THREAD

**Issue by matthilde** [Mw3y/SNT-Website#2]
Your website is not compatible with smaller displays. Is this site designed for 4K displays?

Screenshots:
https://i.cutebunni.es/ZO1sl.png
https://i.cutebunni.es/lN1BA.png

Website has been tested on Firefox (Linux) on a 1680x1050 display.

**Comment by Mw3y** [comment]
Hey, sorry for the late response. It should be working fine with smaller displays now.
